# Site settings
title: WEEMOVE
logo: /assets/img/weemove-logo-black.svg
email: we@weemove.fi
description: "Tarjoamme lapsellesi hauskan liikuntakokemuksen joka antaa onnistumisen tunteita ja kasvattaa lapsen itseluottamusta"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weemove.fi" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-66809541-1
date_format: "%-d.%-m.%Y"
facbook: https://www.facebook.com/Funktum

# Build settings
markdown: kramdown
permalink: /:title/
sass:
  sass_dir: _scss
  style: compressed

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /blog/:title/

# Blog settings
paginate: 10
paginate_path: "/blog/page/:num/"
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/weemove-share-1.png

# Disqus - enable for commenting on blog
# disqus:
#   shortname: EXAMPLE

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
